blank_issues_enabled: true
contact_links:
  - name: Support
    url: https://github.com/orgs/BlueprintFramework/discussions/new?category=support
    about: Receive community-support with anything Blueprint.
